### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by patzila** [gazugafan/laravel-temporal#2]
Any plans on supporting laravel 6?

For the time being, I'll just fork it 
https://github.com/patzila/laravel-temporal

**Comment by gazugafan** [comment]
Nothing in the works at the moment. I haven't had a chance to dig into v6 yet, and probably won't for a long while unfortunately. If you're able to get this working in a backwards compatible way, feel free to send a pull request! Otherwise, I can just update the readme to mention your v6 fork.

**Comment by dsgrillo** [comment]
For what I've tested, there is no need to update anything in the library itself to upgrade to Laravel 6 (besides updating the requirements on composer.json and small tweeks on the tests.)

#3

**Comment by gazugafan** [comment]
Thanks! Just merged the pull request and released v2.0.0.
