### ISSUE TITLE
How to use when we have a recursive relationship?

### ISSUE THREAD

**Issue by Mohammad-Alavi** [gazugafan/laravel-temporal#5]
How to use this package when a model have a recursive relationship with itself?
```
Schema::create('wares', function (Blueprint $table) {
        $table->increments('id');
	$table->unsignedInteger('parent_id');
	$table->foreign('parent_id')->references('id')->on('wares');
}
```

**Comment by gazugafan** [comment]
I don't think you would need to do anything special for this. Do you get an error or something when you run ```Gazugafan\Temporal\Migration::make_temporal('wares');```?

**Comment by Mohammad-Alavi** [comment]
For now i insert this two fields
```
	$table->unsignedInteger('parent_id');
	$table->foreign('parent_id')->references('id')->on('wares');
```
after

	`Gazugafan\Temporal\Migration::make_temporal('wares');`

this way
```
	Schema::table('wares', function ($table) {
		$table->unsignedInteger('parent_id')->nullable();
		$table->foreign('parent_id')->references('id')->on('wares')->onDelete('cascade');
	});
```

**Comment by Mohammad-Alavi** [comment]
Yea i get this error when i run `Gazugafan\Temporal\Migration::make_temporal('wares')`:

` SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'wares_parent_id_foreign' of table 'homestead.wares' (SQL: ALTER TABLE `wares` DROP PRIMARY KEY, MODIFY `id` int(10) unsigned NOT NULL;)
`

**Comment by Mohammad-Alavi** [comment]
When i insert reference to foreign  fields after `make_temporal()` everything works fine but now i get

`Illuminate\Database\QueryException : SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error (SQL: SHOW COLUMNS FROM `wares`;)`

and none of my test work because i get this error every time tests run migration.

**Comment by gazugafan** [comment]
Hmm... yeah, you may need to adjust things manually, then. Just be sure you end up with the columns and indexes mentioned here... https://github.com/gazugafan/laravel-temporal#schema-migration

**Comment by Mohammad-Alavi** [comment]
Yea i checked. I got every field and indexes.
But what do you think about error i mentioned in my[ previous comment](https://github.com/gazugafan/laravel-temporal/issues/5#issuecomment-617970783)?

Thank you for the time you are putting into this btw. I really appreciate it.

**Comment by gazugafan** [comment]
Not sure... the ```SHOW COLUMNS FROM wares;``` query seems perfectly fine to me. Does everything work outside migrations?

**Comment by Mohammad-Alavi** [comment]
Yea everything works but tests. All test fails when they try to run 
`refreshInMemoryDatabase()` of RefreshDatabase trait with the error that i mentioned.

**Comment by gazugafan** [comment]
Are your tests using MySQL? refreshInMemoryDatabase sounds like it's using SQLite, which definitely won't work with this.

If your tests are using MySQL, maybe there's something that's not compatible with Laravel 7? You could trying hacking at https://github.com/gazugafan/laravel-temporal/blob/f9783ef90e1029cbfe559b7ed092ab6feaa6653e/src/Migration.php which is where the make_temporal migration is done.

**Comment by Mohammad-Alavi** [comment]
I was using sqlite in phpunit configs. Changed it to mysql and everything works now.
Just remember to comment
`<server name="DB_DATABASE" value=":memory:"/>`
as mysql doesn't work with this option.
