### ISSUE TITLE
Can't install on Laravel 7.x

### ISSUE THREAD

**Issue by giacomopiva** [gazugafan/laravel-temporal#7]
Got this error:
  
[InvalidArgumentException]                                                                                                                                                                       
  Could not find a matching version of package gazugafan/laravel-temporal@2.0. Check the package spelling, your version constraint and that the package is available in a stability which matches  
   your minimum-stability (dev).

**Comment by gazugafan** [comment]
The composer syntax was wrong in the README. Should be a : instead of an @ before the version number. Try this...
```
composer require gazugafan/laravel-temporal:2.0
```

**Comment by giacomopiva** [comment]
Thank you for your response.
I'm getting this error:

  Problem 1
    - Root composer.json requires gazugafan/laravel-temporal ^2.0 -> satisfiable by gazugafan/laravel-temporal[2.0.0].
    - gazugafan/laravel-temporal 2.0.0 requires illuminate/database ^6.0 -> found illuminate/database[v6.0.0, ..., 6.x-dev] but it conflicts with another require.

**Comment by gazugafan** [comment]
I haven't tried this on Laravel 7 at all, but you could try forking this package, updating the dependencies in composer.json to be compatible with Laravel 7's, and see how it goes. Report back if you do!
