### ISSUE TITLE
Laravel 9 Support?

### ISSUE THREAD

**Issue by mstarling** [gazugafan/laravel-temporal#9]
Hi there,
I ran into a problem updating a site to Laravel 9 (from v8)... it seems laravel-temporal@4.0 doesn't like it.
I'm not great with composer, but I think it's down to this:

`gazugafan/laravel-temporal 4.0.0 requires illuminate/events ^8.0 -> satisfiable by illuminate/events[v8.0.0, ..., v8.83.13].`

but...

`laravel/framework replaces illuminate/events and thus cannot coexist with it.`

Is there a way to address this?
Thanks. :)

**Comment by gazugafan** [comment]
Hmm... maybe try forking this repository and removing illuminate/events from composer.json or update it to ^9.0? Might need to do the same with illuminate/database? I still haven't updated from Laravel 5 myself, but it sounds like so far there haven't been any other breaking changes through v8. So hopefully it's just a matter of updating the composer.json file. Report back if you get it working :)

**Comment by mstarling** [comment]
Thanks... I think I got it working. Still kinda new to working with composer and Github.
Anyway... the change amounted to making the 'require' block just this:
```
    "require": {
        "php" : ">=7.4.0",
        "doctrine/dbal": "^3.3"
    },
```

Much appreciated.

**Comment by gazugafan** [comment]
Cool!
